"""form engine: skip step for author role

Revision ID: 05e39b313cb4
Revises: e12700947a38
Create Date: 2026-08-10 15:16:17.305087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e39b313cb4'
down_revision = 'e12700947a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_workflow_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skip_for_author_roles_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_workflow_steps', schema=None) as batch_op:
        batch_op.drop_column('skip_for_author_roles_json')

    # ### end Alembic commands ###
