"""Maj formulaire DAF

Revision ID: 068a52b5c548
Revises: 114d53f55048
Create Date: 2026-01-19 10:20:08.069476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '068a52b5c548'
down_revision = '114d53f55048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruitments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid_public', sa.String(length=20), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('WAITING_RH_MGR', 'WAITING_RH_DIR', 'REFUSED', 'DISPATCHED', 'DONE', name='recruitmentstatus'), nullable=True),
    sa.Column('date_entree', sa.DateTime(), nullable=True),
    sa.Column('nom_agent', sa.String(length=100), nullable=True),
    sa.Column('prenom_agent', sa.String(length=100), nullable=True),
    sa.Column('fonction', sa.String(length=100), nullable=True),
    sa.Column('service_agent', sa.String(length=100), nullable=True),
    sa.Column('uf_agent', sa.String(length=50), nullable=True),
    sa.Column('contractuel', sa.Boolean(), nullable=True),
    sa.Column('date_debut_contrat', sa.DateTime(), nullable=True),
    sa.Column('date_fin_contrat', sa.DateTime(), nullable=True),
    sa.Column('condition_recrutement', sa.String(length=50), nullable=True),
    sa.Column('temps_travail', sa.String(length=50), nullable=True),
    sa.Column('pourcentage_temps', sa.String(length=20), nullable=True),
    sa.Column('motif_recrutement', sa.String(length=50), nullable=True),
    sa.Column('simulation_salaire', sa.Boolean(), nullable=True),
    sa.Column('localisation_poste', sa.String(length=100), nullable=True),
    sa.Column('commentaire_securite', sa.Text(), nullable=True),
    sa.Column('imago_active', sa.Boolean(), nullable=True),
    sa.Column('imago_mobilite', sa.String(length=200), nullable=True),
    sa.Column('materiels_demandes', sa.String(length=255), nullable=True),
    sa.Column('acces_informatique', sa.Text(), nullable=True),
    sa.Column('file_cv', sa.String(length=255), nullable=True),
    sa.Column('file_fiche_poste', sa.String(length=255), nullable=True),
    sa.Column('file_photo', sa.String(length=255), nullable=True),
    sa.Column('refusal_reason', sa.Text(), nullable=True),
    sa.Column('child_tickets_ids', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recruitments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recruitments_uid_public'), ['uid_public'], unique=True)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('fcpi_date_entree')
        batch_op.drop_column('fcpi_nom')
        batch_op.drop_column('fcpi_badge_commentaire')
        batch_op.drop_column('fcpi_imago_sites')
        batch_op.drop_column('fcpi_statut_secu')
        batch_op.drop_column('fcpi_temps_travail')
        batch_op.drop_column('fcpi_service')
        batch_op.drop_column('fcpi_contractuel')
        batch_op.drop_column('fcpi_date_fin_contrat')
        batch_op.drop_column('fcpi_date_debut_contrat')
        batch_op.drop_column('fcpi_imago_active')
        batch_op.drop_column('fcpi_simulation_salaire')
        batch_op.drop_column('fcpi_acces_info')
        batch_op.drop_column('fcpi_materiel_json')
        batch_op.drop_column('fcpi_pourcentage')
        batch_op.drop_column('fcpi_prenom')
        batch_op.drop_column('fcpi_statut_info')
        batch_op.drop_column('fcpi_statut_imago')
        batch_op.drop_column('fcpi_condition')
        batch_op.drop_column('fcpi_motif')
        batch_op.drop_column('fcpi_file_photo')
        batch_op.drop_column('fcpi_file_poste')
        batch_op.drop_column('fcpi_fonction')
        batch_op.drop_column('fcpi_statut_drh')
        batch_op.drop_column('fcpi_uf')
        batch_op.drop_column('fcpi_file_cv')
        batch_op.drop_column('fcpi_localisation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcpi_localisation', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_file_cv', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_uf', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_statut_drh', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_fonction', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_file_poste', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_file_photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_motif', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_condition', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_statut_imago', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_statut_info', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_prenom', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_pourcentage', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_materiel_json', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_acces_info', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_simulation_salaire', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_imago_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_date_debut_contrat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_date_fin_contrat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_contractuel', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_service', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_temps_travail', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_statut_secu', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_imago_sites', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_badge_commentaire', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_nom', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_date_entree', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('recruitments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recruitments_uid_public'))

    op.drop_table('recruitments')
    # ### end Alembic commands ###
