"""Maj formulaire DAF

Revision ID: 0901c63adb4b
Revises: 118a1f52bf93
Create Date: 2026-01-16 12:31:40.070487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0901c63adb4b'
down_revision = '118a1f52bf93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daf_solver_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('daf_signed_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('daf_signed_file')
        batch_op.drop_column('daf_solver_file')

    # ### end Alembic commands ###
