"""Maj formulaire DAF

Revision ID: 118a1f52bf93
Revises: 2eecb37fbc37
Create Date: 2026-01-16 11:17:44.884755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118a1f52bf93'
down_revision = '2eecb37fbc37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daf_uf', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('daf_budget_affecte', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('daf_new_supplier', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('daf_siret', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('daf_fournisseur_tel_comment', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('daf_rib_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('daf_rib_file')
        batch_op.drop_column('daf_fournisseur_tel_comment')
        batch_op.drop_column('daf_siret')
        batch_op.drop_column('daf_new_supplier')
        batch_op.drop_column('daf_budget_affecte')
        batch_op.drop_column('daf_uf')

    # ### end Alembic commands ###
