"""Maj formulaire DAF

Revision ID: 153533dd96a0
Revises: 4acfea4b356b
Create Date: 2026-01-16 13:58:18.712033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153533dd96a0'
down_revision = '4acfea4b356b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('daf_uf')
        batch_op.drop_column('daf_rib_file')
        batch_op.drop_column('daf_budget_line')
        batch_op.drop_column('daf_signed_file')
        batch_op.drop_column('daf_fournisseur_is_new')
        batch_op.drop_column('daf_solver_file')
        batch_op.drop_column('daf_siret')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daf_siret', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('daf_solver_file', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('daf_fournisseur_is_new', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('daf_signed_file', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('daf_budget_line', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('daf_rib_file', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('daf_uf', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
