"""structured field templates for combined ticket fields

Revision ID: 227f035ffb6e
Revises: 34d8ee82118c
Create Date: 2026-08-10 16:10:09.450697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227f035ffb6e'
down_revision = '34d8ee82118c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('structured_field_templates_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_definitions', schema=None) as batch_op:
        batch_op.drop_column('structured_field_templates_json')

    # ### end Alembic commands ###
