"""form engine: conditional fields, selective file routing

Revision ID: 2318c0975d01
Revises: 05e39b313cb4
Create Date: 2026-08-10 15:30:39.041445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2318c0975d01'
down_revision = '05e39b313cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_dispatch_targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('included_file_fields_json', sa.Text(), nullable=True))

    with op.batch_alter_table('form_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition_field_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('condition_value', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'form_fields', ['condition_field_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_fields', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('condition_value')
        batch_op.drop_column('condition_field_id')

    with op.batch_alter_table('form_dispatch_targets', schema=None) as batch_op:
        batch_op.drop_column('included_file_fields_json')

    # ### end Alembic commands ###
