"""Ajout groupes JSON et workflow N2

Revision ID: 2eecb37fbc37
Revises: faea908d11f5
Create Date: 2026-01-13 11:05:40.578128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2eecb37fbc37'
down_revision = 'faea908d11f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin_services_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('allowed_services_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.drop_column('service_department')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_department', postgresql.ENUM('INFO', 'DAF', 'GEN', 'TECH', 'ENLEV', name='servicetype'), autoincrement=False, nullable=True))
        batch_op.drop_column('location')
        batch_op.drop_column('allowed_services_json')
        batch_op.drop_column('origin_services_json')

    # ### end Alembic commands ###
