"""form engine: ticket templates, uid suffix, field mapping

Revision ID: 34d8ee82118c
Revises: 2318c0975d01
Create Date: 2026-08-10 16:00:20.123126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d8ee82118c'
down_revision = '2318c0975d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_dispatch_targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_category_template', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ticket_title_template', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ticket_description_template', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('uid_suffix', sa.String(length=20), nullable=True))

    with op.batch_alter_table('form_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maps_to_ticket_field', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_fields', schema=None) as batch_op:
        batch_op.drop_column('maps_to_ticket_field')

    with op.batch_alter_table('form_dispatch_targets', schema=None) as batch_op:
        batch_op.drop_column('uid_suffix')
        batch_op.drop_column('ticket_description_template')
        batch_op.drop_column('ticket_title_template')
        batch_op.drop_column('ticket_category_template')

    # ### end Alembic commands ###
