"""add final recipient to form_definitions

Revision ID: 40156aa9747d
Revises: fb29677b0ee5
Create Date: 2026-08-10 13:07:15.469854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '40156aa9747d'
down_revision = 'fb29677b0ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_recipient_role', postgresql.ENUM('USER', 'MANAGER', 'DIRECTEUR', 'SOLVER', 'ADMIN', name='userrole', create_type=False), nullable=True))
        batch_op.add_column(sa.Column('final_recipient_service', postgresql.ENUM('INFO', 'DAF', 'GEN', 'TECH', 'DRH', 'SECU', 'AUTRE', 'IMAGO', 'ACCUEIL', 'ARCHIPELLE', 'CELLULE_PARCOURS', 'CSD', 'DG', 'EAM_DRAVEIL', 'ESAT', 'ESPACE_LOISIRS', 'FH', 'FJ', 'FV', 'GITE', 'IME_CORBEIL', 'MAGASIN', 'MAS', 'MAS_EXTERNAT', 'MAS_INCLUSIVE', 'PATRIMOINE', 'QUALITE', 'SACAT', 'SAMSAH', 'SAVIE', 'SECURITE_INCENDIE', 'SESSAD_CORBEIL', 'SESSAD_CRETEIL', 'SESSAD_TSA', 'SG', 'SRU', 'SYNDICAT', 'TKITOI', 'UEEA', 'UEMA', name='servicetype', create_type=False), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_definitions', schema=None) as batch_op:
        batch_op.drop_column('final_recipient_service')
        batch_op.drop_column('final_recipient_role')

    # ### end Alembic commands ###
