"""ajout champs DAF

Revision ID: 40399454cb1c
Revises: 6f0998762008
Create Date: 2026-04-15 12:42:22.950029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40399454cb1c'
down_revision = '6f0998762008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daf_denomination', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('daf_reference_devis', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('daf_reference_devis')
        batch_op.drop_column('daf_denomination')

    # ### end Alembic commands ###
