"""Maj formulaire DAF

Revision ID: 4acfea4b356b
Revises: 0901c63adb4b
Create Date: 2026-01-16 13:35:55.525552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4acfea4b356b'
down_revision = '0901c63adb4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daf_budget_line', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('daf_fournisseur_is_new', sa.Boolean(), nullable=True))
        batch_op.drop_column('daf_budget_affecte')
        batch_op.drop_column('daf_fournisseur_tel_comment')
        batch_op.drop_column('daf_new_supplier')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daf_new_supplier', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('daf_fournisseur_tel_comment', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('daf_budget_affecte', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('daf_fournisseur_is_new')
        batch_op.drop_column('daf_budget_line')

    # ### end Alembic commands ###
