"""ajout file_dossier_signe sejour

Revision ID: 6779b9688a42
Revises: cdf248a1d22b
Create Date: 2026-04-17 15:03:03.341106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6779b9688a42'
down_revision = 'cdf248a1d22b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dossiers_sejour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_dossier_signe', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dossiers_sejour', schema=None) as batch_op:
        batch_op.drop_column('file_dossier_signe')

    # ### end Alembic commands ###
