"""Ajout DRH et DDM

Revision ID: 6f0998762008
Revises: a7f8fe4f2491
Create Date: 2026-01-20 14:49:21.067449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0998762008'
down_revision = 'a7f8fe4f2491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rdv_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('rdv_date')

    # ### end Alembic commands ###
