"""Creation formulaire FCPI

Revision ID: a0c4c67305ee
Revises: f94c753e54db
Create Date: 2026-01-16 15:49:19.587110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c4c67305ee'
down_revision = 'f94c753e54db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcpi_date_entree', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fcpi_nom', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fcpi_prenom', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fcpi_fonction', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fcpi_service', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fcpi_uf', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fcpi_contractuel', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('fcpi_date_debut_contrat', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fcpi_date_fin_contrat', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fcpi_condition', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fcpi_temps_travail', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fcpi_pourcentage', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('fcpi_motif', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fcpi_simulation_salaire', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fcpi_localisation', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('fcpi_badge_commentaire', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fcpi_imago_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fcpi_imago_sites', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('fcpi_acces_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fcpi_materiel_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fcpi_file_cv', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('fcpi_file_poste', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('fcpi_file_photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('fcpi_statut_drh', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fcpi_statut_secu', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fcpi_statut_info', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fcpi_statut_imago', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('fcpi_statut_imago')
        batch_op.drop_column('fcpi_statut_info')
        batch_op.drop_column('fcpi_statut_secu')
        batch_op.drop_column('fcpi_statut_drh')
        batch_op.drop_column('fcpi_file_photo')
        batch_op.drop_column('fcpi_file_poste')
        batch_op.drop_column('fcpi_file_cv')
        batch_op.drop_column('fcpi_materiel_json')
        batch_op.drop_column('fcpi_acces_info')
        batch_op.drop_column('fcpi_imago_sites')
        batch_op.drop_column('fcpi_imago_active')
        batch_op.drop_column('fcpi_badge_commentaire')
        batch_op.drop_column('fcpi_localisation')
        batch_op.drop_column('fcpi_simulation_salaire')
        batch_op.drop_column('fcpi_motif')
        batch_op.drop_column('fcpi_pourcentage')
        batch_op.drop_column('fcpi_temps_travail')
        batch_op.drop_column('fcpi_condition')
        batch_op.drop_column('fcpi_date_fin_contrat')
        batch_op.drop_column('fcpi_date_debut_contrat')
        batch_op.drop_column('fcpi_contractuel')
        batch_op.drop_column('fcpi_uf')
        batch_op.drop_column('fcpi_service')
        batch_op.drop_column('fcpi_fonction')
        batch_op.drop_column('fcpi_prenom')
        batch_op.drop_column('fcpi_nom')
        batch_op.drop_column('fcpi_date_entree')

    # ### end Alembic commands ###
