"""Creation formulaire FCPI

Revision ID: bf90708aee1c
Revises: a0c4c67305ee
Create Date: 2026-01-16 15:54:49.211063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf90708aee1c'
down_revision = 'a0c4c67305ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('fcpi_file_poste')
        batch_op.drop_column('fcpi_temps_travail')
        batch_op.drop_column('fcpi_statut_imago')
        batch_op.drop_column('fcpi_badge_commentaire')
        batch_op.drop_column('fcpi_fonction')
        batch_op.drop_column('fcpi_statut_secu')
        batch_op.drop_column('fcpi_acces_info')
        batch_op.drop_column('fcpi_imago_sites')
        batch_op.drop_column('fcpi_simulation_salaire')
        batch_op.drop_column('fcpi_motif')
        batch_op.drop_column('fcpi_pourcentage')
        batch_op.drop_column('fcpi_contractuel')
        batch_op.drop_column('fcpi_date_entree')
        batch_op.drop_column('fcpi_file_cv')
        batch_op.drop_column('fcpi_date_fin_contrat')
        batch_op.drop_column('fcpi_statut_drh')
        batch_op.drop_column('fcpi_file_photo')
        batch_op.drop_column('fcpi_localisation')
        batch_op.drop_column('fcpi_statut_info')
        batch_op.drop_column('fcpi_prenom')
        batch_op.drop_column('fcpi_service')
        batch_op.drop_column('fcpi_nom')
        batch_op.drop_column('fcpi_materiel_json')
        batch_op.drop_column('fcpi_uf')
        batch_op.drop_column('fcpi_imago_active')
        batch_op.drop_column('fcpi_condition')
        batch_op.drop_column('fcpi_date_debut_contrat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcpi_date_debut_contrat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_condition', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_imago_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_uf', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_materiel_json', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_nom', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_service', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_prenom', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_statut_info', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_localisation', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_file_photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_statut_drh', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_date_fin_contrat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_file_cv', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_date_entree', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_contractuel', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_pourcentage', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_motif', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_simulation_salaire', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_imago_sites', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_acces_info', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_statut_secu', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_fonction', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_badge_commentaire', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_statut_imago', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_temps_travail', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fcpi_file_poste', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
