"""ajout dossiers_sejour et publications

Revision ID: cdf248a1d22b
Revises: 40399454cb1c
Create Date: 2026-04-17 14:53:45.586687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf248a1d22b'
down_revision = '40399454cb1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('daf_denomination')
        batch_op.drop_column('daf_reference_devis')

    # IF EXISTS : `password_hash` n'a jamais existé dans la chaîne de
    # migrations elle-même (colonne héritée d'un schéma créé via
    # db.create_all() avant l'initialisation d'Alembic) — absente si cette
    # migration est rejouée depuis une base totalement vierge (ex: base de
    # dev), présente en prod. Rend la migration idempotente dans les deux cas.
    op.execute('ALTER TABLE users DROP COLUMN IF EXISTS password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daf_reference_devis', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('daf_denomination', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
