"""add assigned_at to tickets

Revision ID: dea2e0a6d97c
Revises: 227f035ffb6e
Create Date: 2026-08-11 09:55:11.062132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea2e0a6d97c'
down_revision = '227f035ffb6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('assigned_at')

    # ### end Alembic commands ###
