"""form engine: multi dispatch targets, manager_only, multi_select

Revision ID: e12700947a38
Revises: f507ce630386
Create Date: 2026-08-10 14:09:53.476421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e12700947a38'
down_revision = 'f507ce630386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Alembic ne diff pas les valeurs d'un enum Postgres existant : ajout manuel.
    op.execute("ALTER TYPE formfieldtype ADD VALUE IF NOT EXISTS 'MULTI_SELECT'")

    op.create_table('form_dispatch_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_definition_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('target_service', postgresql.ENUM('INFO', 'DAF', 'GEN', 'TECH', 'DRH', 'SECU', 'AUTRE', 'IMAGO', 'ACCUEIL', 'ARCHIPELLE', 'CELLULE_PARCOURS', 'CSD', 'DG', 'EAM_DRAVEIL', 'ESAT', 'ESPACE_LOISIRS', 'FH', 'FJ', 'FV', 'GITE', 'IME_CORBEIL', 'MAGASIN', 'MAS', 'MAS_EXTERNAT', 'MAS_INCLUSIVE', 'PATRIMOINE', 'QUALITE', 'SACAT', 'SAMSAH', 'SAVIE', 'SECURITE_INCENDIE', 'SESSAD_CORBEIL', 'SESSAD_CRETEIL', 'SESSAD_TSA', 'SG', 'SRU', 'SYNDICAT', 'TKITOI', 'UEEA', 'UEMA', name='servicetype', create_type=False), nullable=False),
    sa.Column('condition_field_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['condition_field_id'], ['form_fields.id'], ),
    sa.ForeignKeyConstraint(['form_definition_id'], ['form_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_only', sa.Boolean(), nullable=True))
        batch_op.drop_column('target_service')

    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_ids_json', sa.Text(), nullable=True))
        batch_op.drop_constraint(batch_op.f('form_submissions_ticket_id_fkey'), type_='foreignkey')
        batch_op.drop_column('ticket_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('form_submissions_ticket_id_fkey'), 'tickets', ['ticket_id'], ['id'])
        batch_op.drop_column('ticket_ids_json')

    with op.batch_alter_table('form_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_service', postgresql.ENUM('INFO', 'DAF', 'GEN', 'TECH', 'DRH', 'SECU', 'AUTRE', 'IMAGO', 'ACCUEIL', 'ARCHIPELLE', 'CELLULE_PARCOURS', 'CSD', 'DG', 'EAM_DRAVEIL', 'ESAT', 'ESPACE_LOISIRS', 'FH', 'FJ', 'FV', 'GITE', 'IME_CORBEIL', 'MAGASIN', 'MAS', 'MAS_EXTERNAT', 'MAS_INCLUSIVE', 'PATRIMOINE', 'QUALITE', 'SACAT', 'SAMSAH', 'SAVIE', 'SECURITE_INCENDIE', 'SESSAD_CORBEIL', 'SESSAD_CRETEIL', 'SESSAD_TSA', 'SG', 'SRU', 'SYNDICAT', 'TKITOI', 'UEEA', 'UEMA', name='servicetype', create_type=False), autoincrement=False, nullable=True))
        batch_op.drop_column('manager_only')

    op.drop_table('form_dispatch_targets')
    # ### end Alembic commands ###
