"""form engine: emitter service source, target_service, ticket link

Revision ID: f507ce630386
Revises: 40156aa9747d
Create Date: 2026-08-10 13:26:44.033369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f507ce630386'
down_revision = '40156aa9747d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    service_source_enum = postgresql.ENUM('FIXED', 'EMITTER', name='servicesource')
    service_source_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('form_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_service', postgresql.ENUM('INFO', 'DAF', 'GEN', 'TECH', 'DRH', 'SECU', 'AUTRE', 'IMAGO', 'ACCUEIL', 'ARCHIPELLE', 'CELLULE_PARCOURS', 'CSD', 'DG', 'EAM_DRAVEIL', 'ESAT', 'ESPACE_LOISIRS', 'FH', 'FJ', 'FV', 'GITE', 'IME_CORBEIL', 'MAGASIN', 'MAS', 'MAS_EXTERNAT', 'MAS_INCLUSIVE', 'PATRIMOINE', 'QUALITE', 'SACAT', 'SAMSAH', 'SAVIE', 'SECURITE_INCENDIE', 'SESSAD_CORBEIL', 'SESSAD_CRETEIL', 'SESSAD_TSA', 'SG', 'SRU', 'SYNDICAT', 'TKITOI', 'UEEA', 'UEMA', name='servicetype', create_type=False), nullable=True))
        batch_op.drop_column('final_recipient_role')
        batch_op.drop_column('final_recipient_service')

    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tickets', ['ticket_id'], ['id'])

    with op.batch_alter_table('form_workflow_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_source', postgresql.ENUM('FIXED', 'EMITTER', name='servicesource', create_type=False), nullable=False, server_default='FIXED'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_workflow_steps', schema=None) as batch_op:
        batch_op.drop_column('service_source')

    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ticket_id')

    with op.batch_alter_table('form_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_recipient_service', postgresql.ENUM('INFO', 'DAF', 'GEN', 'TECH', 'DRH', 'SECU', 'AUTRE', 'IMAGO', 'ACCUEIL', 'ARCHIPELLE', 'CELLULE_PARCOURS', 'CSD', 'DG', 'EAM_DRAVEIL', 'ESAT', 'ESPACE_LOISIRS', 'FH', 'FJ', 'FV', 'GITE', 'IME_CORBEIL', 'MAGASIN', 'MAS', 'MAS_EXTERNAT', 'MAS_INCLUSIVE', 'PATRIMOINE', 'QUALITE', 'SACAT', 'SAMSAH', 'SAVIE', 'SECURITE_INCENDIE', 'SESSAD_CORBEIL', 'SESSAD_CRETEIL', 'SESSAD_TSA', 'SG', 'SRU', 'SYNDICAT', 'TKITOI', 'UEEA', 'UEMA', name='servicetype', create_type=False), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('final_recipient_role', postgresql.ENUM('USER', 'MANAGER', 'DIRECTEUR', 'SOLVER', 'ADMIN', name='userrole', create_type=False), autoincrement=False, nullable=True))
        batch_op.drop_column('target_service')

    # ### end Alembic commands ###

    postgresql.ENUM(name='servicesource').drop(op.get_bind(), checkfirst=True)
