"""Maj formulaire DAF

Revision ID: f94c753e54db
Revises: 153533dd96a0
Create Date: 2026-01-16 14:02:24.366110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f94c753e54db'
down_revision = '153533dd96a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daf_uf', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('daf_budget_affecte', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('daf_new_supplier', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('daf_siret', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('daf_fournisseur_tel_comment', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('daf_rib_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('daf_solver_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('daf_signed_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('daf_signed_file')
        batch_op.drop_column('daf_solver_file')
        batch_op.drop_column('daf_rib_file')
        batch_op.drop_column('daf_fournisseur_tel_comment')
        batch_op.drop_column('daf_siret')
        batch_op.drop_column('daf_new_supplier')
        batch_op.drop_column('daf_budget_affecte')
        batch_op.drop_column('daf_uf')

    # ### end Alembic commands ###
