"""add dynamic form engine tables

Revision ID: fb29677b0ee5
Revises: 6779b9688a42
Create Date: 2026-08-10 12:41:03.981678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'fb29677b0ee5'
down_revision = '6779b9688a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_definitions_slug'), ['slug'], unique=True)

    op.create_table('form_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_definition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('field_type', sa.Enum('TEXT', 'TEXTAREA', 'DATE', 'SELECT', 'CHECKBOX', 'NUMBER', 'FILE', 'MULTI_FILE', name='formfieldtype'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('options_json', sa.Text(), nullable=True),
    sa.Column('help_text', sa.String(length=255), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['form_definition_id'], ['form_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_definition_id', 'name', name='uq_form_field_name')
    )
    op.create_table('form_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid_public', sa.String(length=40), nullable=True),
    sa.Column('form_definition_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('current_step_index', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'REFUSED', 'DONE', name='formsubmissionstatus'), nullable=True),
    sa.Column('refusal_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['form_definition_id'], ['form_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_submissions_uid_public'), ['uid_public'], unique=True)

    op.create_table('form_workflow_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_definition_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('validator_role', postgresql.ENUM('USER', 'MANAGER', 'DIRECTEUR', 'SOLVER', 'ADMIN', name='userrole', create_type=False), nullable=True),
    sa.Column('validator_service', postgresql.ENUM('INFO', 'DAF', 'GEN', 'TECH', 'DRH', 'SECU', 'AUTRE', 'IMAGO', 'ACCUEIL', 'ARCHIPELLE', 'CELLULE_PARCOURS', 'CSD', 'DG', 'EAM_DRAVEIL', 'ESAT', 'ESPACE_LOISIRS', 'FH', 'FJ', 'FV', 'GITE', 'IME_CORBEIL', 'MAGASIN', 'MAS', 'MAS_EXTERNAT', 'MAS_INCLUSIVE', 'PATRIMOINE', 'QUALITE', 'SACAT', 'SAMSAH', 'SAVIE', 'SECURITE_INCENDIE', 'SESSAD_CORBEIL', 'SESSAD_CRETEIL', 'SESSAD_TSA', 'SG', 'SRU', 'SYNDICAT', 'TKITOI', 'UEEA', 'UEMA', name='servicetype', create_type=False), nullable=True),
    sa.ForeignKeyConstraint(['form_definition_id'], ['form_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_submission_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=60), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_submission_files')
    op.drop_table('form_workflow_steps')
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_submissions_uid_public'))

    op.drop_table('form_submissions')
    op.drop_table('form_fields')
    with op.batch_alter_table('form_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_definitions_slug'))

    op.drop_table('form_definitions')
    # ### end Alembic commands ###
